# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upgXXSBG_ekzQ19pvcmFQ9XZAr6LP0PM
"""

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import gdown
import os

# download model from Google Drive if not already available
if not os.path.exists("scene_model.h5"):
    url = "https://drive.google.com/uc?id=1B1DXQnYtruQCh6auof-J5pR89PXxiPG3"
    gdown.download(url, "scene_model.h5", quiet=False)

# check if model file exists
if os.path.exists("scene_model.h5"):
    model = load_model("scene_model.h5")
else:
    st.error("Model file not found. Please check the download link.")

# class labels (same as dataset folder names)
class_names = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']

# app title
st.title("Natural Scene Classification")

# file upload
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:

    # load and preprocess image
    img = image.load_img(uploaded_file, target_size=(100, 100))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # predict
    prediction = model.predict(img_array)
    pred_index = np.argmax(prediction)

    # display result
    st.image(uploaded_file, caption="Uploaded Image")
    st.write("Predicted Scene:", class_names[pred_index])

