# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upgXXSBG_ekzQ19pvcmFQ9XZAr6LP0PM
"""

import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import gdown
import os

# download model from Google Drive if not already present
if not os.path.exists("scene_model.h5"):
    url = "https://drive.google.com/file/d/18vYalPqYASGaxgS4eZLiZypk-4Z-TwEw/view?usp=drive_link"
    gdown.download(url, "scene_model.h5", quiet=False)

# load model
model = load_model("scene_model.h5")

class_names = ['buildings', 'forest', 'glacier', 'mountain', 'sea', 'street']

st.title("Natural Scene Classification")

uploaded_file = st.file_uploader("Upload image", type=["jpg","png","jpeg"])

if uploaded_file is not None:
    img = image.load_img(uploaded_file, target_size=(100,100))
    img_array = image.img_to_array(img)/255.0
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)
    st.image(uploaded_file)
    st.write("Prediction:", class_names[np.argmax(prediction)])

